/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
/**
 *
 * @author DELL
 */
public class Register_DateTime extends javax.swing.JFrame {

    String aa="";
    
    /**
     * Creates new form Register_DateTime
     */
    public Register_DateTime() {
        initComponents();
    }

    public Register_DateTime(String para){
        initComponents();
        jDateChooser1.setDate(Calendar.getInstance().getTime());
        
        aa=para;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Schedule");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "10am-12pm", "1pm-3pm", "3pm-5pm", "5pm-7pm" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 171, 103, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Register Date");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 262, 103, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Date");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 97, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Time slot");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 174, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/WhatsApp Image 2021-05-10 at 1.25.00 AM.jpeg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(7000, 500));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date dt1=jDateChooser1.getDate();
        String str=(String)sdf.format(dt1);
        String time=(String)jComboBox1.getSelectedItem();
       
        
        try
       {
           Class.forName("java.sql.DriverManager");
            Connection con=(Connection)
                    
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/vaccine","root","Karan@22");
                    Statement stmt=(Statement)con.createStatement();
                    String q1="select user_id from login where aadhar_no="+aa+"";
                    ResultSet rs=stmt.executeQuery(q1);
                    String y="Done";
                    String st="Pending";
                    if(rs.next())
                    {
                        String c="0";
                        String x=rs.getString("user_id");
                        String q6="select count(app_id) from appointment where user_id='"+x+"' group by user_id;";
                        ResultSet rs2=stmt.executeQuery(q6);
                        if(rs2.next())
                        {
                            c=rs2.getString("count(app_id)");
                                                        
                        }
                        
                        if("0".equals(c))
                        {
                            String q7="insert into appointment values(null,'"+x+"','"+str+"', '"+time+"','"+st+"'); ";
                            stmt.executeUpdate(q7);
                            this.dispose();
                            new Confirmation(str,time).setVisible(true);
                        }
                        if("1".equals(c))
                        {
                           // System.out.print(c);
                            String q8="select app_id from appointment where user_id='"+x+"' and status='"+y+"';";
                            ResultSet rs3=stmt.executeQuery(q8);
                            if(rs3.next())
                            {
                                  String q9="insert into appointment values(null,'"+x+"','"+str+"', '"+time+"','"+st+"'); ";
                                    stmt.executeUpdate(q9);
                                    this.dispose();
                                    new Confirmation(str,time).setVisible(true);
                            }
                            else if(!rs3.next())
                            {
                                System.out.print(c+"p");
                                String q5="select app_id from appointment where user_id='"+x+"' and status='"+st+"';";
                                ResultSet rs1=stmt.executeQuery(q5);
                                 if(rs1.next())
                                {
                                    String x1=rs1.getString("app_id");
                                    this.dispose();
                                    Update nf4=new Update(x1);
                                    nf4.setVisible(true);
                                }
                            }
                        }
                       if("2".equals(c))
                       {
                           String q5="select app_id from appointment where user_id='"+x+"' and status='"+st+"';";
                                ResultSet rs1=stmt.executeQuery(q5);
                                 if(rs1.next())
                                {
                                    String x1=rs1.getString("app_id");
                                    this.dispose();
                                    Update nf5=new Update(x1);
                                    nf5.setVisible(true);
                                }
                                else
                                 {
                                     JOptionPane.showMessageDialog(this,"You have completed your vaccination doses");
                                 }
                       }
                       
                        
                    }
                    
                    
       }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_DateTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_DateTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_DateTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_DateTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_DateTime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
